### ISSUE TITLE
Migirate repo to CYF Infrastructure

### ISSUE THREAD

**Issue by momahboobian** [CodeYourFuture/good-pr#181]
**Background**
Good PR repo needs to be migrated to the CYF Infrastructure Good PR repo
Depends on #192 192

**Acceptance criteria**
1. Migrate the repo from Natalie's to [Good PR Repository](https://github.com/CodeYourFuture/good-pr) CYF Infrastructure
2. Support DevOps in the migration

**Comment by kfklein15** [comment]
Duplicated https://github.com/CodeYourFuture/good-pr/issues/187
