### ISSUE TITLE
Create Github Actions pipeline for Docker

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/good-pr#192]
**Background**
There was a change to the scope of ticket https://github.com/CodeYourFuture/devops_team/issues/34 so that the GitHub Actions pipeline has now being created by the Good PR team.

**Acceptance criteria**
- Have a simple docker build working on a GitHub action
- Deploy the [Docker file](https://github.com/CodeYourFuture/good-pr/blob/main/Dockerfile)

[PR #193 ](https://github.com/CodeYourFuture/good-pr/pull/193)

**Comment by kfklein15** [comment]
This has been done, right? So I will close this ticket.

**Comment by kfklein15** [comment]
Is there anything pending for this ticket, @CodeYourFuture/devops ?

**Comment by craig-dsilva** [comment]
We need to create an IAM user for the pipeline (see [#53)](https://github.com/CodeYourFuture/devops_team/issues/54).
