### ISSUE TITLE
[Spike] Design cohort view for NW6 and WM5

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/good-pr#210]
**Background**
We want to use Good PR for NW6 and WM5, so it would be good if we could separate the projects per team. In order to do that, we want to know what it could look like.

**Acceptance criteria**
- User must select a cohort (hardcoded for MVP) when signing up OR logging in (and haven't selected previously)
- Good PR has a view per cohort

**Comment by Farnooshmo** [comment]
![Image](https://github.com/CodeYourFuture/good-pr/assets/91014204/b2b3789b-aee1-4f87-90ae-334055900c29)

**Comment by kfklein15** [comment]
- Create a new landing page AND make it the home page
- Show only the right cohort teams by clicking on the cohort button


Updating the data
- Set a spreadsheet with the data we need (Google Sheets)
- Script to upload the data
